### ISSUE TITLE
factionsuuid placeholders disappeared

### ISSUE THREAD

**Issue by Wqrld** [PlaceholderAPI-Expansions/Expansion-Suggestions#2]
### Expansion Name
factionsuuid
### Expansion Plugin URL
https://www.spigotmc.org/resources/factionsuuid.1035/
httpss://www.spigotmc.org/resources/savagefactions-f-fly-f-upgrades-f-checkpoint-f-warp-gui.52891/
### Possible Placeholders
/papi parse %factionsuuid_player_name%
### Why Would It Be Beneficial?
because a lot of people are using factionsuuid but its not in the ecloud anymore

**Comment by Banbeucmas** [comment]
What? https://api.extendedclip.com/expansions/factions/

**Comment by DoNotSpamPls** [comment]
FactionsUUID already has PlaceholderAPI integration, but they don't use the extension cloud, but instead it's in their plugin. The code can be found [here](https://github.com/drtshock/Factions/blob/1.6.x/src/main/java/com/massivecraft/factions/util/ClipPlaceholderAPIManager.java)

SavageFactions is a stupid FUUID ripoff, don't bother with that.

**Comment by Banbeucmas** [comment]
That's harsh. :p

**Comment by Wqrld** [comment]
but then how do i parse these placeholders? i cant seem to use factionsuuid_placeholder

**Comment by Wqrld** [comment]
@extendedclip could you then add savagefactions as a separate module in the ecloud? I really want to use it for my server.

**Comment by extendedclip** [comment]
Savage factions should provide it's own placeholders as well.

**Comment by Wqrld** [comment]
prosavage(the dev) is saying that the same class is included but it doesnt work

**Comment by extendedclip** [comment]
Did you try the correct placeholder? He changed the identifier to "savagefactions" instead of "factions"  or "factionsuuid". Smh

**Comment by Wqrld** [comment]
@extendedclip can you add support for player_role_prefix?
he's saying you need to do something too.
https://cdn.discordapp.com/attachments/422130071902617611/430734297062834184/unknown.png
